---
name: Publish Docker
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: docker/login-action@v4
        with:
          username: {{dockerhub_username}}
          password: $\{{ secrets.{{github_token_prefix}}_DOCKERHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          image: cliffano/studio:4.0.0
          shell: bash
          extra_args: '-v ~/.docker/config.json:/root/.docker/config.json:ro'
          command: |
            make clean deps lint build-docker &&
            cat logs/packer-build-docker.log &&
            docker --version &&
            docker info  &&
            docker inspect {{dockerhub_username}}/{{image_name}} &&
            make publish-docker